public enum CommandType : ushort
{
	None = 0,
	Build = 1,
	Attack = 2,
	Recover = 3,
	HealOthers = 4,
	Train = 5,
	Move = 6,
	Capture = 7,
	Research = 8,
	Destroy = 9,
	Disband = 10,
	CityReward = 11,
	Promote = 13,
	ExamineRuins = 14,
	EndTurn = 15,
	Upgrade = 16,
	FreezeArea = 17,
	BreakIce = 18,
	SelectTribe = 19,
	StartMatch = 20,
	Stay = 21,
	EndMatch = 22,
	Harvest = 23,
	Explode = 24,
	Boost = 25,
	Decompose = 26,
	PeaceTreaty = 27,
	PeaceRequestResponse = 28,
	BreakPeace = 29,
	EstablishEmbassy = 30,
	Clone = 31,
	UpgradeEmbassy = 32,
	Hide = 33,
	InfiltrateReward = 34,
	Resign = 35
}
