[project]
name = "polyterra-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pettingzoo>=1.25.0",
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
    "wandb>=0.24.1",
    "sb3-contrib>=2.7.1",
    "tensorboard>=2.20.0",
    "ray[rllib]>=2.53.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["polyterra_env*"]
